Fix release workflow for pre-releases (#113)
## Summary

fixes: #34

Reference:
https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=published#release

> `prerelease` boolean Required
>
> Whether the release is identified as a prerelease or a full release.

This PR also fixes a bug where the "build-id" job wouldn't fail when the
`build.generate_build_id` script would fail because of
https://www.shellcheck.net/wiki/SC2155. As the build-id job wouldn't
fail, the workflow will continue with the next job to build the
extension but that would fail because it doesn't have the build ID
([reference
workflow](https://github.com/astral-sh/ty-vscode/actions/runs/16142723204/job/45553733677#step:4:25)).
It's fixed by avoiding to `export` and instead assigning the script
output to a variable first.

## Test Plan

Run `actionlint`, which also runs `shellcheck`.

I also ran the build-id generation script locally to verify the code
works. Here's the local script:

```sh
prerelease="true"

if [[ "$prerelease" = "true" ]]; then
  build_id="$(python -m build.generate_build_id --pre-release)"
else
  build_id="$(python -m build.generate_build_id)"
fi

echo "build-id: ${build_id}"
```

When `prerelease` is `"true"`:
```console
$ bash t.sh                      
build-id: 12200640
```

When `prerelease` is `"false"`, it fails successfully:
```console
$ bash t.sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/dhruv/work/astral/ty-vscode/build/generate_build_id.py", line 71, in <module>
    main(PACKAGE_JSON_PATH, pre_release=args.pre_release)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dhruv/work/astral/ty-vscode/build/generate_build_id.py", line 49, in main
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Release version should have EVEN numbered minor version: 2025.33.0
build-id: 
```

And, when I manually update the version number to an even number in
`package.json`:
```console
$ bash t.sh
build-id: 0
```